# Compiler and flags
CC = clang
FLAGS = -lncursesw

# Directories
SRC_DIR = src
BUILD_DIR = build
SRC_FILES := $(shell find $(SRC_DIR) -name '*.c')
OBJ_FILES := $(patsubst $(SRC_DIR)/%.c,$(BUILD_DIR)/%.o,$(SRC_FILES))

# Binary
BIN = bin/bin

